### ISSUE TITLE
[BUG] Crash on placing a pixel.

### ISSUE THREAD

**Issue by theishiopian** [dantaeusb-mc/Zetter#10]
Attempting to paint on a server crashes the client

stacktrace:

```
Description: Unexpected error

java.lang.NoClassDefFoundError: javafx/util/Pair
	at com.dantaeusb.zetter.container.EaselContainer.processSync(EaselContainer.java:497) ~[zetter:0.9.8-1.16.3-rc] {re:classloading}
	at com.dantaeusb.zetter.network.ClientHandler.processCanvasSync(ClientHandler.java:39) ~[zetter:0.9.8-1.16.3-rc] {re:classloading}
	at com.dantaeusb.zetter.network.packet.SCanvasSyncMessage.lambda$handle$0(SCanvasSyncMessage.java:66) ~[zetter:0.9.8-1.16.3-rc] {re:classloading}
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[forge:?] {re:mixin,re:classloading}
	at com.dantaeusb.zetter.network.packet.SCanvasSyncMessage.handle(SCanvasSyncMessage.java:66) ~[zetter:0.9.8-1.16.3-rc] {re:classloading}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[forge:?] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_242] {}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[forge:?] {re:mixin,re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:91) ~[forge:?] {re:mixin,re:classloading}
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_242] {}
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:91) ~[forge:?] {re:mixin,re:classloading}
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1904) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59) ~[?:?] {re:classloading}
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:36) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default}
	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:189) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:151) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:128) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184)
```

**Comment by theishiopian** [comment]
This issue is present on version 0.9.8, and 0.9.7 as well.

Server Log:
[latest.log](https://github.com/dantaeusb-mc/Zetter/files/6767384/latest.log)

Client Log:
[latest.log](https://github.com/dantaeusb-mc/Zetter/files/6767387/latest.log)

Crash Report:
[crash-2021-07-05_21.57.05-client.txt](https://github.com/dantaeusb-mc/Zetter/files/6767388/crash-2021-07-05_21.57.05-client.txt)

**Comment by dantaeusb** [comment]
Apparently, javafx does not exist on any environment, which I was unaware of. Thanks for the report! I've replaced it with an alternative data type, it looks like that works well. Going to upload new version to CurseForge in a moment.

**Comment by dantaeusb** [comment]
Ok, version 0.9.9 was just approved on CurseForge, that should fix the issue, as there's no other javafx dependencies as far as I concerned. Feel free to reopen this / open another issue if you encounter another problem on your environment.

**Comment by theishiopian** [comment]
Tested with 0.9.9, the issue seems fixed so far. I will let you know if it comes back
