### ISSUE TITLE
Artist Table TE Slot Mismatch Error

### ISSUE THREAD

**Issue by dantaeusb** [dantaeusb-mc/Zetter#12]
On dedicated server startup:
```
[16:13:34] [Server thread/ERROR] [minecraft/TileEntity]: Failed to load data for block entity zetter:artist_table_tile_entity
java.lang.IllegalArgumentException: Corrupted NBT: Number of inventory slots did not match expected.
        at com.dantaeusb.zetter.tileentity.ArtistTableTileEntity.func_230337_a_(ArtistTableTileEntity.java:79) ~[?:0.10.4-1.16.3-rc] {re:classloading}
        at net.minecraft.tileentity.TileEntity.lambda$func_235657_b_$1(TileEntity.java:88) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at java.util.Optional.map(Unknown Source) ~[?:1.8.0_301] {}
        at net.minecraft.tileentity.TileEntity.func_235657_b_(TileEntity.java:86) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.world.chunk.storage.ChunkSerializer.func_222650_a(ChunkSerializer.java:400) ~[?:?] {re:classloading}
        at net.minecraft.world.chunk.storage.ChunkSerializer.lambda$read$2(ChunkSerializer.java:133) ~[?:?] {re:classloading}
        at net.minecraft.world.chunk.Chunk.func_217318_w(Chunk.java:457) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ChunkManager.lambda$null$25(ChunkManager.java:582) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[?:?] {re:classloading}
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?] {re:classloading}
        at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[?:?] {re:classloading}
        at net.minecraft.world.server.ChunkManager.lambda$func_219200_b$26(ChunkManager.java:569) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at java.util.concurrent.CompletableFuture.uniApply(Unknown Source) ~[?:1.8.0_301] {}
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:1.8.0_301] {}
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_301] {}
        at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213166_h(SourceFile:545) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(SourceFile:554) ~[?:?] {re:classloading}
        at net.minecraft.world.server.ServerChunkProvider.func_217234_d(SourceFile:280) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:706) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:692) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213186_a(MinecraftServer.java:465) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:307) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:164) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:616) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_301] {}
```

**Comment by dantaeusb** [comment]
Doesn't block server startup and works just fine on dedicated server, seems like, so not critical

**Comment by dantaeusb** [comment]
Artist Table container/item handlers changed in 0.17
